services:
  server:
    build: .
    container_name: instasend-server
    volumes:
      - ./data:/data
    env_file: .env
    restart: unless-stopped
    networks:
      - edge

networks:
  edge:
    external: true
